### ISSUE TITLE
Filtering on 'Created' isn't consistent. 

### ISSUE THREAD

**Issue by techmsa** [Educ-IO/educ-io#7]
When filtering on the 'Created' field the results are not consistent. If I have created dates of 1/29/2022, 2/29/2022, 4/29/2021, and 5/19/2022 and I put the value 29 in the filter field, I will get all of them including the 5/19/2022 records. 
If I try to narrow it down and put in the full date value I get no results. I tried both with and without the slashes.  Maybe I'm doing something incorrectly?

**Comment by thiscouldbejd** [comment]
Hi!

Apologies for the late response!

As it's a sort of text field underneath, if you filter using [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format dates (e.g. YYYY-MM-DD) then it should work in the way you expect! If not - let me know :)

Yours,

JD

**Comment by techmsa** [comment]
That worked.


Thanks,


Pinkney Webster

Technical Support


MileStone Academy

www.MileStone-Academy.org <http://www.milestone-academy.org/>

215 663 1160 Office

215 817 8849 Mobile

**Comment by thiscouldbejd** [comment]
Glad it's working for you! Will close this issue, but get in touch if there are any further issues :)
